services:
  api:
    build:
      context: .
      dockerfile: nest/Dockerfile
    container_name: api
    ports:
      - '3000:3000'
    env_file:
      - ./nest/.env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    volumes:
      - ./nest/upload:/api/nest/upload
      - ./nest/logs:/api/nest/logs
      - ./nest/public:/api/nest/public
      - ./nest/certs:/api/nest/certs
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - '6379:6379'
  web:
    build:
      context: .
      dockerfile: vue/Dockerfile
    ports:
      - '8080:80'
    depends_on:
      - api
      - nginx
  nginx:
    image: nginx:latest
    depends_on:
      - api
      - web
    ports:
      - '8080:8080'
    volumes:
      - ./vue/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./vue/certs:/etc/nginx/certs:ro
      - ./vue/dist:/usr/share/nginx/html:ro
