version: '3.9'
services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - '6379:6379'
  api:
    build:
      context: .
      dockerfile: nest/Dockerfile
    container_name: api
    ports:
      - '3000:3000'
    env_file:
      - ./nest/.env
    depends_on:
      - redis
    volumes:
      - ./nest/upload:/app/nest/upload
      - ./nest/logs:/app/nest/logs
      - ./nest/public:/app/nest/public
      - ./nest/certs:/app/nest/certs
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - '8080:80'
    depends_on:
      - api
